# name
name: 'model_my160'

# directory
data_dir: '../../motion_transfer_data/processed_bfa'
data_norm_dir: '../../motion_transfer_data/processed_bfa'

motion_length: 160

# model options
model:
    gen:
        # content encoder
        enc_in_dim: 12
        enc_nf: 64
        latent_dim: 128
        
        # for graph convolution
        graph:
            joint: {'layout': 'cmu', 'strategy': 'distance', 'max_hop': 2}
            mid: {'layout': 'cmu', 'strategy': 'distance', 'max_hop': 1}
            bodypart: {'layout': 'cmu', 'strategy': 'distance', 'max_hop': 1}

# training arguments
manualSeed: 1777
num_workers: 0 #8
batch_size: 32
lr_gen: 0.0001
weight_decay: 0.0001
max_epochs: 300 #10

# weight for objective functions
rec_w: 1
cyc_con_w: 0.5
cyc_sty_w: 0.5
sm_rec_w: 1
sm_cyc_w: 1

# step size
log_every: 5       # iter
save_every: 10       # epoch

device: 'cuda:1'